services:
  bot:
    build: .
    container_name: clinicafisina_telegram_bot
    volumes:
      - .:/app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME_FISINA=${DB_NAME_FISINA}
      - DB_NAME_LOGS=${DB_NAME_LOGS}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PREFIX=${REDIS_PREFIX}
    depends_on:
      - redis
    networks:
      - redis_net

networks:
  redis_net:
    external: true
