services:
  bot:
    build: .
    container_name: clinicafisina_telegram_bot
    volumes:
      - .:/app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - redis
    networks:
      - redis_net

networks:
  redis_net:
    external: true
