services:
  bot:
    image: ghcr.io/jorgeavlobo/clinicafisina-telegram-bot:latest
    container_name: clinicafisina_telegram_bot
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME_FISINA=${DB_NAME_FISINA}
      - DB_NAME_LOGS=${DB_NAME_LOGS}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis_fsm
      - REDIS_PORT=6379
      - REDIS_DB=${REDIS_DB}
      - REDIS_PREFIX=${REDIS_PREFIX}
    networks:
      - redis_net

networks:
  redis_net:
    external:
      name: redis_redis_net
