services:
  bot:
    image: ghcr.io/jorgeavlobo/clinicafisina-telegram-bot:latest
    container_name: clinicafisina_telegram_bot
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

    # <<< change host port to 8444
    ports:
      - "127.0.0.1:8444:8443"

    networks:
      - redis_net

networks:
  redis_net:
    external: true
    name: redis_redis_net
